[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "booster_robotics_sdk"
version = "0.1.0"
description = "Booster robotics SDK bindings"
requires-python = ">=3.8,<3.13"

[tool.setuptools.packages.find]
include = ["booster_robotics_sdk"]

[tool.setuptools.package-data]
booster_robotics_sdk = ["booster_robotics_sdk_python.cpython-*.so", "libddsc.so*", "libddscxx.so*", "libfastcdr.so*", "libfastrtps.so*", "libtinyxml2.so*"]